version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: on-failure
    network_mode: host
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/server.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - swagger

  swagger:
    image: swaggerapi/swagger-ui:latest
    container_name: swagger
    restart: on-failure
    network_mode: host
